// Generated by CoffeeScript 1.6.3
(function() {
  var Cheerio, FS, Hogan, Path,
    __hasProp = {}.hasOwnProperty;

  FS = require("fs");

  Path = require("path");

  Cheerio = require("cheerio");

  Hogan = require("hogan.js");

  exports.compile = function(args, options) {
    var $, $templates, assignTo, code, html, htmlFile, js, jsDir, jsFile, jsName, name, selector, templates, _i, _len, _results;
    if (options == null) {
      options = {};
    }
    assignTo = options.assignTo || "window.compiledTemplates";
    selector = options.selector || "script[type='text/x-mustache-template']";
    _results = [];
    for (_i = 0, _len = args.length; _i < _len; _i++) {
      htmlFile = args[_i];
      html = FS.readFileSync(htmlFile, {
        encoding: "utf8"
      });
      $ = Cheerio.load(html);
      $templates = $(selector);
      templates = {};
      $templates.each(function(element) {
        return templates[this.attr("id")] = Hogan.compile(this.text(), {
          asString: true
        });
      });
      js = [];
      js.push("" + assignTo + " = {}");
      for (name in templates) {
        if (!__hasProp.call(templates, name)) continue;
        code = templates[name];
        js.push("" + assignTo + "[\"" + name + "\"] = new Hogan.Template(" + code + ");");
      }
      js = js.join("\n") + "\n";
      jsDir = options.dir || Path.dirname(htmlFile);
      jsName = Path.basename(htmlFile, Path.extname(htmlFile));
      jsFile = Path.join(jsDir, jsName + "-templates.js");
      _results.push(FS.writeFileSync(jsFile, js));
    }
    return _results;
  };

}).call(this);
